RobotName: "reemc"

GazeboXBotPlugin:
  control_rate: 0.001
  gains:
    arm_left_1_joint: {p: 1000, d: 10}
    arm_left_2_joint: {p: 1000, d: 10}
    arm_left_3_joint: {p: 1000, d: 10}
    arm_left_4_joint: {p: 1000, d: 10}
    arm_left_5_joint: {p: 1000, d: 10}
    arm_left_6_joint: {p: 1000, d: 10}
    arm_left_7_joint: {p: 1000, d: 10}
    arm_right_1_joint: {p: 1000, d: 10}
    arm_right_2_joint: {p: 1000, d: 10}
    arm_right_3_joint: {p: 1000, d: 10}
    arm_right_4_joint: {p: 1000, d: 10}
    arm_right_5_joint: {p: 1000, d: 10}
    arm_right_6_joint: {p: 1000, d: 10}
    arm_right_7_joint: {p: 1000, d: 10}
    head_1_joint: {p: 1000, d: 10}
    head_2_joint: {p: 1000, d: 10}
    leg_left_1_joint: {p: 1000, d: 10}
    leg_left_2_joint: {p: 1000, d: 10}
    leg_left_3_joint: {p: 1000, d: 10}
    leg_left_4_joint: {p: 1000, d: 10}
    leg_left_5_joint: {p: 1000, d: 10}
    leg_left_6_joint: {p: 1000, d: 10}
    leg_right_1_joint: {p: 1000, d: 10}
    leg_right_2_joint: {p: 1000, d: 10}
    leg_right_3_joint: {p: 1000, d: 10}
    leg_right_4_joint: {p: 1000, d: 10}
    leg_right_5_joint: {p: 1000, d: 10}
    leg_right_6_joint: {p: 1000, d: 10}
    torso_1_joint: {p: 1000, d: 10}
    torso_2_joint: {p: 1000, d: 10}

HALInterface:
  lib_file: "libXBotEcat"
  lib_name: "ETHERCAT"
  IJoint: "libXBotEcat_Joint"
  IEndEffectors:
   - [[19,29] , "libXBotEcat_SoftHand"]
  ISensors:
   - [[18,28,147,157], "libXBotEcat_FT"]
   - [[91], "libXBotEcat_IMU"]
  

  
##### OTHER R-HAL SPECIFIC DATA