joint_map:
    1: l_ankle_pitch
    2: l_ankle_roll
    3: l_elbow
    4: l_hip_pitch
    5: l_hip_roll
    6: l_hip_yaw
    7: l_knee
    8: l_shoulder_pitch
    9: l_shoulder_roll
    10: l_shoulder_yaw
    11: l_wrist_pitch
    12: l_wrist_prosup
    13: l_wrist_yaw
    14: neck_pitch
    15: neck_roll
    16: neck_yaw
    17: r_ankle_pitch
    18: r_ankle_roll
    19: r_elbow
    20: r_hip_pitch
    21: r_hip_roll
    22: r_hip_yaw
    23: r_knee
    24: r_shoulder_pitch
    25: r_shoulder_roll
    26: r_shoulder_yaw
    27: r_wrist_pitch
    28: r_wrist_prosup
    29: r_wrist_yaw
    30: torso_pitch
    31: torso_roll
    32: torso_yaw
