XBotCore:
  config_path: "external/tutorial_iros2018/configs/reemc/xbotcore/reemc_config.yaml"

XBotInterface:
  urdf_path: "external/tutorial_iros2018/robots/reemc/reemc.urdf"
  srdf_path: "external/tutorial_iros2018/robots/reemc/reemc.srdf"
  joint_map_path: "external/tutorial_iros2018/configs/reemc/joint_id_map/reemc_joint_map.yaml"

RobotInterface:
  framework_name: "ROS"

ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "true"
  
MasterCommunicationInterface:
  framework_name: "ROS"

XBotRTPlugins:
  plugins: ["HomingExample", "simpleIK", "GcompPlugin", "simpleID", "simpleOS"]
  io_plugins: []
  
NRTPlugins:
  plugins: []

TransmissionPlugins:
  plugins: [] 
  
WebServer:
  enable: "false"
  address: "127.0.0.1"
  port: "8081"

SimulationOptions:
  verbose_mode: "true"
